# Generated by Django 2.2.4 on 2019-08-31 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_header', models.CharField(max_length=50, verbose_name='Заголовок новости')),
                ('news_content', models.TextField(verbose_name='Содержание новости')),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='news_images', verbose_name='Изображение новости')),
                ('news_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время новости')),
                ('news_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор новости')),
                ('news_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='News.NewsCategory', verbose_name='Категория новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
