# Generated by Django 2.2.4 on 2019-09-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_image',
        ),
    ]
