# Generated by Django 2.2.5 on 2019-10-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0002_auto_20191024_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание экзамена'),
        ),
    ]
