# Generated by Django 2.2.5 on 2019-10-27 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0004_auto_20191024_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_images', verbose_name='Изображение вопроса')),
                ('question_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.Exam', verbose_name='Вопрос к экзамену')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'exam_questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Текст ответа')),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='answer_images', verbose_name='Изображение ответа')),
                ('answer_truth', models.BooleanField(verbose_name='Истинность ответа')),
                ('answer_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.Question', verbose_name='Ответ к вопросу')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'exam_answers',
            },
        ),
    ]
